### ISSUE TITLE
Specifying JsonSerializerSettings for complex types

### ISSUE THREAD

**Issue by PaulRReynolds** [giometrix/TableStorage.Abstractions.TableEntityConverters#4]
I've been using your `TableStorage.Abstractions.POCO` library, and it's been really useful for getting over the hurdle of storing POCO types into Table Storage, thanks!

One issue I've run into is that there are times where default serializer settings aren't quite enough for certain types I'd like to store within a table. It would be great if there were some way to specify a `JsonSerializerSettings` object to be used for serializing/deserializing into Json columns within the table. Is this something you've considered for the library? One issue might be the fact that the To/From methods are static, so may require an additional parameter to make this work.

Thanks again for your work on this library!

Paul

**Comment by giometrix** [comment]
Json serialization options have been added in v1.4.

They'll be exposed in TableStorage.Abstractions.POCO shortly.

Thanks for the suggestion!
